### ISSUE TITLE
Can't get message when app is terminated

### ISSUE THREAD

**Issue by kurt-liao** [rithik-dev/firebase_notifications_handler#2]
Hi, thanks for creating this project, it works nice.

I copy your sample code and test, it works when the app is open, 
but I can not receive message when the app is terminated, have any idea for this?

By the way, I use it in android.

**Comment by rithik-dev** [comment]
Hey, @kurt-liao, if you're using the "Send notification after 5s" button from the sample app, and you're terminating the app in that 5s duration, so, it won't work, as the event never triggers. That button works for testing if the notification arrives when the app is in the background (not terminated).

However, if you're facing an issue in a real world scenario, then make sure you've gone through the documentation, and if you are still facing an issue, please share some logs/ code snippets so I can see what exactly you're doing, and why doesn't it work...

**Comment by kurt-liao** [comment]
Thanks for replying. I figure out that I have the wrong settings in firebase.

**Comment by rithik-dev** [comment]
Hey @kurt-liao, that's great!

Do you mind sharing what the actual issue was? like what setting did you change for this to work?

**Comment by kurt-liao** [comment]
Hi @rithik-dev, I got the issue mentioned [here](https://flutterhq.com/questions-and-answers/2414/firebase-cloud-messaging-is-not-working-after-publishing-android-app-in-play-store)

Just because I did not generate a sha1 key. Obviously, it's no association with your project😅

BTW, thanks for your patience!

**Comment by rithik-dev** [comment]
Oh, got it. 

Thanks for letting me know the issue, will try to improve the documentation accordingly..
