### ISSUE TITLE
add option to disable foreground notification?

### ISSUE THREAD

**Issue by himsarevenus** [rithik-dev/firebase_notifications_handler#5]
need to disable foreground notification in some cases

**Comment by rithik-dev** [comment]
Hey @himsarevenus, you can switch to the `major-refactor` branch, which has a handler `shouldHandleNotification` which can be used to disable foreground notifications.

**Comment by rithik-dev** [comment]
I am planning to release a version in some time, some things are left to be polished before merge and release...

**Comment by rithik-dev** [comment]
Hey @himsarevenus, I'm releasing v2.0.0 of the package which will contain the mentioned feature. It's also a major refactor and things are now quite stable than before.

**Comment by rithik-dev** [comment]
Hey @himsarevenus, the new version [v2.0.0](https://pub.dev/packages/firebase_notifications_handler/versions/2.0.0) is live.
