### ISSUE TITLE
update firebase messaging dependancy

### ISSUE THREAD

**Issue by computerfriendlog2** [rithik-dev/firebase_notifications_handler#6]
Please update the code. its not cometible with new firebase_messaging

**Comment by himsarevenus** [comment]
any update on this ?

**Comment by rithik-dev** [comment]
Hey @computerfriendlog2 @himsarevenus , I'm releasing v2.0.0 of the package which will fix the mentioned issue. It's also a major refactor and things are now quite stable than before.

**Comment by rithik-dev** [comment]
Hey @computerfriendlog2 @himsarevenus, the new version [v2.0.0](https://pub.dev/packages/firebase_notifications_handler/versions/2.0.0) is live.
