### ISSUE TITLE
Please update all plugins

### ISSUE THREAD

**Issue by Praveencodenex** [rithik-dev/firebase_notifications_handler#7]

**Comment by rithik-dev** [comment]
Hey @Praveencodenex , I'm releasing v2.0.0 of the package which will fix the mentioned issue. It's also a major refactor and things are now quite stable than before.

**Comment by rithik-dev** [comment]
Hey @Praveencodenex, the new version [v2.0.0](https://pub.dev/packages/firebase_notifications_handler/versions/2.0.0) is live.
